name: diz que disse
favicon: null
layout_spectrum: 0.26933
typography_spectrum: 0.29871
title: diz que disse
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d3d3b'
    - '#130908'
    - '#7e7863'
    - '#56513f'
    - '#9a9580'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
